### PR TITLE
Parametrize `workflow_dispatch` to allow choosing `environment`

### PR DESCRIPTION
**Pull request by michalinacienciala**
We want to be able to deploy the dashboard manually using both Sepolia and Goerli based configs.
We'll deploy using Sepolia config on pushes to `main` or when triggered manually with `sepolia` environment input.
We'll deploy using Goerli config when triggered manually with the `goerli` environment input.

### CODE REVIEW

**Comment by michalinacienciala** [comment]
Test run of the workflow: https://github.com/threshold-network/bitcoin-on-base/actions/runs/7740148802

**Comment by michalinacienciala** [comment]
Another test run, after fixing one problem: https://github.com/threshold-network/bitcoin-on-base/actions/runs/7740309506

**Review by lukasz-zimnoch — DISMISSED** [review]
LGTM!

**Comment by michalinacienciala** [comment]
Another deployment: https://github.com/threshold-network/bitcoin-on-base/actions/runs/7742204935. Job finished successfully, but https://bob.test.threshold.network/ shows empty page for me.
In logs I see:
```
inpage.js:373 Uncaught TypeError: Cannot redefine property: ethereum
    at Function.defineProperties (<anonymous>)
    at inpage.js:373:27354
    at inpage.js:373:28297
    at inpage.js:373:28301

15:14:16.325 index.ts:53 Uncaught Error: Unsupported chain id
    at new e (index.ts:53:13)
    at Object._initialize (index.ts:16:22)
    at new e (index.ts:11:10)
    at 128 (getThresholdLib.ts:61:10)
    at a ((index):1:1575)
    at 993 (main.8a43d177.chunk.js:1:1298276)
    at a ((index):1:1575)
    at t ((index):1:1444)
    at Array.r [as push] ((index):1:1307)
    at main.8a43d177.chunk.js:1:79
```
Looks there's still some problem with the config 🤔

**Comment by michalinacienciala** [comment]
Ok, we finally got there!
Here's the deployment job: https://github.com/threshold-network/bitcoin-on-base/actions/runs/7742827748
And here's the testnet BoB dapp: https://bob.test.threshold.network

**Review by lukasz-zimnoch — APPROVED** [review]

**Pull request merged**
